import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Check, Clock, Cloud, FileText, Music, Play, RotateCcw, Square, Video, Volume2 } from 'lucide-react';

type Tab = 'workspace' | 'media' | 'pdf' | 'sounds';
const STORAGE = 'VICTMATE_PREFERENCES_V1';

export default function App() {
  const [tab, setTab] = useState<Tab>('workspace');
  const [seconds, setSeconds] = useState(25 * 60);
  const [running, setRunning] = useState(false);
  const [sessions, setSessions] = useState(0);
  const [notes, setNotes] = useState('');
  const [tasks, setTasks] = useState([{text:'Complete a focused study session',done:false},{text:'Summarize key concepts',done:false}]);
  const [video, setVideo] = useState('jfKfPfyJRdk');
  const [sound, setSound] = useState(false);
  const [pdf, setPdf] = useState<string | null>(null);

  useEffect(() => { const saved = localStorage.getItem(STORAGE); if (saved) { try { const p=JSON.parse(saved); setNotes(p.notes||''); setTasks(p.tasks||tasks); setSessions(p.sessions||0); } catch {} } }, []);
  useEffect(() => { localStorage.setItem(STORAGE, JSON.stringify({notes,tasks,sessions})); }, [notes,tasks,sessions]);
  useEffect(() => { if (!running) return; const id=window.setInterval(()=>setSeconds(s=>{ if(s<=1){setRunning(false);setSessions(n=>n+1);return 25*60;} return s-1; }),1000); return ()=>clearInterval(id); }, [running]);
  const time = useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`,[seconds]);
  const embed = (value:string) => { const m=value.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/); return m?.[1] || (value.length===11 ? value : 'jfKfPfyJRdk'); };
  const nav=[['workspace','Full Workspace',Clock],['media','Media Hub',Video],['pdf','PDF Reader',BookOpen],['sounds','Soundscape',Music]] as const;
  return <div className="min-h-screen"><header className="border-b border-[#EBE4D8] bg-[#FDFBF7] sticky top-0 z-10"><div className="max-w-6xl mx-auto p-4 flex flex-wrap gap-4 items-center justify-between"><div><b className="text-2xl tracking-[.16em]">VICT<span className="text-[#E78A69]">MATE</span></b><div className="text-[10px] uppercase tracking-widest text-[#7A6B68]">Distraction-Free Workspace</div></div><div className="flex gap-1 bg-[#F7F4EE] p-1 rounded-2xl">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-xl text-xs flex gap-1 items-center ${tab===id?'bg-white shadow-sm font-bold':'text-[#7A6B68]'}`}><Icon size={14}/>{label}</button>)}</div><button className="text-xs flex items-center gap-1 text-[#556F4A]"><Cloud size={15}/> Local sync</button></div></header>
  <main className="max-w-6xl mx-auto p-4 md:p-6"><div className="grid gap-5 lg:grid-cols-12"><section className="lg:col-span-5 space-y-5"><Timer time={time} running={running} sessions={sessions} setRunning={setRunning} reset={()=>{setRunning(false);setSeconds(1500)}}/>{(tab==='workspace'||tab==='sounds')&&<Soundscape active={sound} toggle={()=>setSound(!sound)}/>}</section><section className="lg:col-span-7 space-y-5">{(tab==='workspace'||tab==='media')&&<Media video={video} setVideo={setVideo}/>} {(tab==='workspace'||tab==='pdf')&&<Reader pdf={pdf} setPdf={setPdf}/>}<Notes notes={notes} setNotes={setNotes} tasks={tasks} setTasks={setTasks}/></section></div></main></div>;
}
function Card({children}:{children:React.ReactNode}){return <div className="bg-white border border-[#EBE4D8] rounded-3xl p-5 shadow-sm">{children}</div>}
function Timer(p:any){return <Card><div className="flex justify-between items-center"><h2 className="font-semibold">Pomodoro Focus</h2><span className="text-xs text-[#7A6B68]">{p.sessions}/5 sessions</span></div><div className="text-7xl text-center font-serif my-8 text-[#2C1B18]">{p.time}</div><div className="flex gap-2"><button onClick={()=>p.setRunning(!p.running)} className="flex-1 rounded-2xl py-3 bg-[#E78A69] text-white font-semibold flex justify-center gap-2">{p.running?<Square size={16}/>:<Play size={16}/>} {p.running?'Pause':'Start Focus'}</button><button onClick={p.reset} className="p-3 rounded-2xl bg-[#F7F4EE]"><RotateCcw size={17}/></button></div></Card>}
function Media({video,setVideo}:any){const [input,setInput]=useState('');return <Card><h2 className="font-semibold flex gap-2 items-center"><Video size={17} className="text-[#E78A69]"/> Media Player Hub</h2><div className="flex gap-2 mt-4"><input className="flex-1 border border-[#E6DFD5] rounded-xl p-2 text-sm" placeholder="YouTube URL or video ID" value={input} onChange={e=>setInput(e.target.value)}/><button className="px-4 rounded-xl bg-[#E78A69] text-white" onClick={()=>setVideo(input)}>Load</button></div><iframe className="w-full aspect-video rounded-2xl mt-4 bg-black" src={`https://www.youtube-nocookie.com/embed/${video}`} allowFullScreen title="Study media"/></Card>}
function Reader({pdf,setPdf}:any){return <Card><div className="flex justify-between items-center"><h2 className="font-semibold flex gap-2"><BookOpen size={17} className="text-[#E78A69]"/> Study PDF Reader</h2><label className="px-3 py-2 rounded-xl border border-[#2C1B18] text-xs cursor-pointer">Load PDF<input type="file" accept="application/pdf" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)setPdf(URL.createObjectURL(f))}}/></label></div>{pdf?<iframe src={pdf} className="w-full h-[420px] mt-4 rounded-2xl" title="PDF reader"/>:<div className="mt-4 min-h-40 rounded-2xl bg-[#FAF7F0] p-6 text-sm leading-7"><h3 className="text-xl font-serif mb-3">VICTMATE Deep Work Guide</h3><p>Use focused intervals, capture distractions in your scratchpad, and review concepts with spaced retrieval. Load your own PDF to study inside the workspace.</p></div>}</Card>}
function Soundscape({active,toggle}:any){return <Card><div className="flex justify-between items-center"><div><h2 className="font-semibold flex gap-2"><Music size={17} className="text-[#A3B899]"/> Ambient Focus Sounds</h2><p className="text-xs text-[#7A6B68] mt-1">Procedural distraction-free soundscape</p></div><button onClick={toggle} className={`p-3 rounded-xl ${active?'bg-[#A3B899] text-white':'bg-[#F7F4EE]'}`}><Volume2 size={17}/></button></div><div className="grid grid-cols-2 gap-2 mt-4">{['White Noise','Pink Noise','Rainfall','Nature Birds'].map(x=><button key={x} onClick={toggle} className="p-3 rounded-xl bg-[#FAF8F5] text-xs text-left">{active?<Check size={13} className="inline text-[#556F4A]"/>:<span className="inline-block w-3"/>} {x}</button>)}</div></Card>}
function Notes({notes,setNotes,tasks,setTasks}:any){return <Card><h2 className="font-semibold flex gap-2"><FileText size={17} className="text-[#A3B899]"/> Focus Scratchpad</h2><div className="space-y-2 my-3">{tasks.map((t:any,i:number)=><button key={i} onClick={()=>setTasks(tasks.map((x:any,j:number)=>j===i?{...x,done:!x.done}:x))} className="block text-sm"><span className="mr-2">{t.done?'☑':'☐'}</span><span className={t.done?'line-through text-gray-400':''}>{t.text}</span></button>)}</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write notes, formulas, or key concepts..." className="w-full min-h-28 rounded-2xl border border-[#E6DFD5] bg-[#FAF8F5] p-3 text-sm resize-none"/></Card>}
